services:
  # RabbitMQ para comunicación asíncrona
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: bodrido-billing-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"      # AMQP port
      - "15672:15672"    # Management UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # Base de datos exclusiva para Billing (Puerto 5433)
  billing-db:
    image: postgres:16-alpine
    container_name: bodrido-billing-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bodrido_billing_db
    ports:
      - "5433:5432" # Mapeamos 5433 de tu PC al 5432 del contenedor
    volumes:
      - billing_postgres_data:/var/lib/postgresql/data

  # (Opcional) El microservicio
  # billing-ms:
  #   build: .
  #   container_name: bodrido-billing-ms
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - DB_HOST=billing-db
  #     - DB_PORT=5432 # Dentro de la red de docker, la base escucha en 5432
  #     - DB_NAME=bodrido_billing_db
  #     - RABBITMQ_HOST=rabbitmq
  #     - RABBITMQ_PORT=5672
  #     - RABBITMQ_USER=guest
  #     - RABBITMQ_PASSWORD=guest
  #   depends_on:
  #     - billing-db
  #     - rabbitmq

volumes:
  billing_postgres_data:
  rabbitmq_data: